version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    volumes:
      - ./data/:/app/data
      - ./notebooks/:/app/notebooks
      - ./scripts/:/app/scripts
    ports:
        - "8888:8888"
        - "6006:6006"
    env_file:
     - ./sample.env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=8888 --no-browser --allow-root
    